### ISSUE TITLE
Suggestion: Support Node-Based Forced Authentication.

### ISSUE THREAD

**Issue by InteriorCamping** [egg82/2FAPlus#3]
### Use Case
**Background**
For an upcoming project of mine, I would like to be able to force anybody in certain user groups (i.e. staff) to authenticate. Additionally, I would like staff to be able to force certain users to use authentication (i.e. players who file compromised account punishment appeals).

That said, given that the project is a moderately big public server, I do not want to require the remainder of the playerbase to authenticate; 2fa should have no impact on general gameplay.

**Requirements**
Therefore, my use case involves an authentication system that can:
- force anybody with a certain rank to 2fa, regardless of if they use any commands associated with that rank.
- force certain players to 2fa, regardless of if they have access to any commands that would otherwise require 2fa.
- allow 2fa-forced users to register themselves, thereafter not allowing them to remove their own 2fa without contacting an admin.
- allow staff in-game to use a command that assigns people to the list of users forced to authenticate.

### Current Options
**Existing Methods**
To the best of my knowledge, at present, forcing users to use authentication is only possible through one of the following methods:

1. Setting `force-auth: true` in the config.
2. Registering all possible commands that user has access to in the config.
3. Giving the target the `2faplus.check` node and using `2faplus register totp <player>` while the target is online.

**Limitations of Existing Methods** 
Unfortunately, none of the above methods work for my use case because:

1. By forcing all players to use authentication, the player experience for a significant portion of the playerbase is significantly impacted.
2. By requiring registration through certain commands, it becomes impossible to target a singular non-staff user for forced authentication.
3. To the best of my knowledge, this method requires staff be online with the player being added to the forced list. Additionally, this method is unable to target groups of players.

### Possible Additions
To the best of my knowledge, my intended usage is not possible with any current proxy-side plugins. It is, however, possible through the slightly outdated proxy-side [MCAuthenticator](https://github.com/parallelblock/MCAuthenticator) and the paid server-side [MineSecure](https://www.spigotmc.org/resources/minesecure.699/) (md_5's).

**MCAuthenticator**
MCA's system adds an enabling admin cmd, a permission node that allows players to register themselves, and a locking admin cmd (to prevent the player from disabling their auth).

**MineSecure**
md_5's system adds the following nodes:
```yaml
minesecure.2fa #Allow using two factor auth
minesecure.admin #Remove two factor auth from other users
minesecure.required #Force 2fa authentication
minesecure.remove #Remove own 2fa authentication
```
These nodes effectively allow admins to force 2fa for any player or group (through permissions). 

### Conclusion & Request
**Conclusion**
Of the two systems shown above, I believe that the permission based forcing system used in MineSecure is ideal. It allows for quite a few use cases, including mine.

**Request**
If it is not too much trouble, I would like to request the addition of a permission node based forcing system similar to the one implemented in MineSecure.

Thank you.

**Comment by egg82** [comment]
I'm quite late to this, but I'm looking at implementing the MineSecure permission-based system for the next release.

Thanks for the information!

**Comment by egg82** [comment]
Permission node changes:
2faplus.use - allows usage of register, check, and delete commands
2faplus.admin - allows usage of register, check, and delete commands **on other players**

The other perms will stay the same:
2faplus.check - forces the player to use 2FA on login

Notes:
Protected commands still require the player to have 2FA enabled and still require a 2FA code
/hotp command is still technically usable by everyone, but of course does nothing for players without HOTP

This should allow for multiple use-cases, including yours.

**Comment by InteriorCamping** [comment]
Thank you, much appreciated!
